
  #애플리케이션 포트 설정
server:
  port: 8080
  error:
    whitelabel:
      enabled: true
    include-exception: false
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
itemImgLocation: d:/shopimg/item
uploadPath: file:///d:/shopimg/
# DB
spring:
  config:
    activate:
      on-profile:

  profiles:
    include: oauth

  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
#        실행되는 쿼리 콘솔 출력
        format_sql: true
#        콘솔창에 출력되는 쿼리를 가독성이 좋게 포맷팅
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.H2Dialect

  session:
    store-type: jdbc

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: debug

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:tcp://localhost/~/shoptest
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.H2Dialect
