#애플리케이션 포트 설정
server:
  port: 80
  error:
    whitelabel:
      enabled: true

# DB
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
#        실행되는 쿼리 콘솔 출력
        format_sql: true
#        콘솔창에 출력되는 쿼리를 가독성이 좋게 포맷팅
    database-platform: org.hibernate.dialect.H2Dialect


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:tcp://localhost/~/shoptest
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
